sim:
  gui: true 
  timestep: 0.02 
  gravity: -9.81 

world:
  obstacles:
    - {pos: [1.1, -0.1, 0.05], size: [0.35, 0.35, 0.1]}
    - {pos: [1.7, -0.35, 0.05], size: [0.35, 0.25, 0.1]}

  target:
    pos: [2.2, 1.5, 0.02]

  object:
    pos: [2.4, 0.4, 0.03]
